### ISSUE TITLE
Target "OpenXROpenGLExample" links to target "OpenXR::openxr-all-supported" but the target was not found

### ISSUE THREAD

**Issue by adnanmunawar** [ReliaSolve/OpenXR-OpenGL-Example#3]
Hi,

Thank you for putting this project together. I am using Ubuntu 20.04 and have installed the OpenXR SDK. When I run `cmake ..` for this project in its build folder, I get the following error:

```bash
Could NOT find OpenXR (missing: OpenXR_DIR)
Presentation backend selected for hello_xr, loader_test, conformance: xlib
BUILD_WITH_XLIB_HEADERS: ON
BUILD_WITH_XCB_HEADERS: ON
BUILD_WITH_WAYLAND_HEADERS: ON
Configuring done
CMake Error at CMakeLists.txt:76 (add_executable):
  Target "OpenXROpenGLExample" links to target "OpenXR::openxr-all-supported"

  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?

Generating done
```
I am also attaching my CMakeCache.txt file if it helps in any way.
[CMakeCache.txt](https://github.com/ReliaSolve/OpenXR-OpenGL-Example/files/7866253/CMakeCache.txt)

**Comment by russell-taylor** [comment]
It seems like the installer behavior may have changed since I set this up originally; you're the second person to have this problem.  The libraries are still being found for me on Windows but I haven't tried with a recent OpenXR SDK.  I hope to find the time to take a look at this over the weekend.  If you make any progress in the meantime getting this to configure, please let me know.

**Comment by russell-taylor** [comment]
I finally got back around to looking at this. With the current versions of the libraries, that target is no longer needed. I have removed it from the build process and can now build and run on Windows on the HTV Vive.
